1. Updated snake_case_checker to  ignore related_files paths for fileId and fileKey
tetrascience/ts-ids-validator pull request #16
Opened 2021-11-05 14:15 UTC by setiat

fixes #15

2021-11-05 15:02 UTC, mlipschultz requested changes
Overall, looks good.  I have a minor suggestion to make it easier for the customer to use if they want to customize it.

2021-11-05 15:35 UTC, setiat commented on ids_validator/checks/v1/snake_case.py
> +        if node.path in ignored_paths:
Adding a `ignored_path` in construct is a small change and can be done quickly without affecting any timeline.

But I would like to suggest against it, as this  is an isolated case related to conflict between related_files template and  snake_case only. Adding `ignored_paths` in global constructor will give an impression that these paths are ignored by each `checker`

But if we still want to do this...can I rename `ignored_paths` to `snake_case_ignored_paths`?

2021-11-05 15:36 UTC, setiat commented on setup.py
> +VERSION = "0.9.1"
v.0.9.0 was already pushed before I noticed #15

2021-11-05 15:56 UTC, mlipschultz commented on ids_validator/checks/v1/snake_case.py
> +        if node.path in ignored_paths:
You bring up a good point.  This probably wouldn't be needed in most cases.  Maybe once we have a need for it we can discuss implementation.

I'm surprised you'd need to add this to the global constructor, but that's probably because I don't understand/remember how to customize a particular checker.  Why wouldn't it be as simple as modifying `V1SnakeCaseChecker.__init__`?

2021-11-05 15:57 UTC, mlipschultz approved these changes
I have a question just to help me understand, but this looks good to merge.

2021-11-08 07:56 UTC, setiat commented on ids_validator/checks/v1/snake_case.py
> +        if node.path in ignored_paths:
I was thinking that client will be using the validator and not modifying it. Hence passing ignored_paths from CLI/config file to Snake_Case_checker via global constructor made sense.

But if client can modify the code,  `V1SnakeCaseChecker.__init__` would be the place for modification.

2021-11-08 07:56 UTC, merged