DE- 2627: athena checker
tetrascience/ts-ids-validator pull request #20
Opened 2021-11-12 11:47 UTC by setiat

- Added new logic for path normalisation
- added schema validation for Athena.json

2021-11-12 12:35 UTC, mlipschultz reviewed
I'm mostly interested in whether there are tests to confirm the added behavior.

2021-11-12 12:35 UTC, mlipschultz commented on ids_validator/checks/generic/athena.py
> +            normalized_path = normalized_path[:-1]
I think these four lines could be replaced with just a `strip('_')`:
```suggestion
        normalized_path = normalized_path.strip("_")
```

2021-11-12 12:35 UTC, mlipschultz commented on ids_validator/utils.py
> -
It'd be good to keep this so it's consistent with [our coding standards](https://www.python.org/dev/peps/pep-0008/#blank-lines).

2021-11-12 12:35 UTC, mlipschultz commented on ids_validator/checks/generic/athena.py
> +        Weird-partition!@name -> weird_partition_name
Maybe I missed it, but are there tests to confirm the behavior in this method?

2021-11-12 13:17 UTC, setiat commented on ids_validator/checks/generic/athena.py
> +            normalized_path = normalized_path[:-1]
Thanks! Fixed it.

2021-11-12 13:18 UTC, setiat commented on ids_validator/utils.py
> -
added 2 blank lines

2021-11-12 13:18 UTC, setiat commented on ids_validator/checks/generic/athena.py
> +        Weird-partition!@name -> weird_partition_name
added test cases

2021-11-12 13:19 UTC, setiat commented on ids_validator/utils.py
> -
- Two blank lines between the import statements and other code.
- Two blank lines between each function.

right?

2021-11-12 13:39 UTC, mlipschultz commented on ids_validator/utils.py
> -
Right, plus two blank lines between each function or class:
> Surround top-level function and class definitions with two blank lines.

2021-11-12 14:05 UTC, mlipschultz approved these changes

2021-11-18 12:18 UTC, mlipschultz requested changes

2021-11-18 12:18 UTC, mlipschultz commented on ids_validator/checks/generic/athena.py
> +        normalized_path = normalized_path.strip("_")
It looks like only a leading underscore is invalid: https://github.com/tetrascience/ts-lambda-core/blob/development/lambdas/dlToAthena/normalizers/index.js#L18
```suggestion
        normalized_path = normalized_path.lstrip("_")
```

2021-11-22 09:58 UTC, setiat commented on ids_validator/checks/generic/athena.py
> +        normalized_path = normalized_path.strip("_")
fixed

2021-11-22 12:09 UTC, mlipschultz approved these changes

2021-11-23 05:47 UTC, merged