DE-3241: athena checker fix
tetrascience/ts-ids-validator pull request #39
Opened 2022-02-10 13:20 UTC by setiat

Partition path in Athena.json can now be root level property from IDS schema JSON

2022-02-10 20:43 UTC, wkopen requested changes
The code change looks good. But can we add a test for the happy path to test athena path using the top-level field will not fail the validator?

2022-02-11 16:08 UTC, wkopen requested changes
In unit test, you should only add what you need for the test. In this case, you are adding the entire schema but you are only testing the top-level fields. The rest of the code will just be maintenance burden. Please remove what you don't need.

2022-02-14 10:16 UTC, setiat commented
> In unit test, you should only add what you need for the test. In this case, you are adding the entire schema but you are only testing the top-level fields. The rest of the code will just be maintenance burden. Please remove what you don't need.

minimised data all Athena test cases

2022-02-14 17:44 UTC, wkopen requested changes
Thanks for trimming the test case down! Now you've introduced another violation of the rule. Please see my inline comment.

2022-02-14 17:44 UTC, wkopen commented on __tests__/unit/generic/files/athena/valid_root_level_property_partition/athena.json
> +            "path": "root_level_property.nested_property",
According to the rule defined in https://developers.tetrascience.com/docs/ids-design-conventions-athenajson#partition-path, you can't have a nested property in the path. So it's an invalid case. The validator should fail.

2022-02-15 12:13 UTC, setiat commented on __tests__/unit/generic/files/athena/valid_root_level_property_partition/athena.json
> +            "path": "root_level_property.nested_property",
@wkopen,
`root_level_property` is of `object` type and `nested_property` has `string` type. So `"root_level_property.nested_property"` should be a valid Path.

I have renamed `nested_property` to `child_property` as former was misleading.

2022-02-16 12:31 UTC, wkopen commented on __tests__/unit/generic/files/athena/valid_root_level_property_partition/athena.json
> +            "path": "root_level_property.nested_property",
thanks! `nested` is a ES keyword so I guess that's where the confusion is from

2022-02-17 08:31 UTC, merged