DE-3238 update type check
tetrascience/ts-ids-validator pull request #40
Opened 2022-02-15 11:33 UTC by setiat

- Updated `TypeChecker` to make sure child properties contains `type` key
- Updated `RootNodeChecker` to check for the presence of valid type for root node
- Added required testcases
- Trimmed test cases for `RootNodeChecker`

2022-02-16 12:34 UTC, robjhornby-ts requested changes
Nice simple check, glad it's straightforward! I briefly checked the shortened test files too, good to simplify them

2022-02-16 12:34 UTC, robjhornby-ts commented on __tests__/unit/generic/files/type_check/invalid_missing_type.json
> +    "beta": {}
I know it gives the same result, but I'd like to also have a test case where the problem is a typo in a `"type"` or `"$ref"` keyword (e.g. `"kind"` and `"#ref"`). That way we're testing for the specific kind of problem we've seen in IDSs. It seems obvious that it will give the same result, but it's nice to put it in a test case to be certain there's nothing unexpected happening.

Doesn't have to be this test file - wherever makes sense

2022-02-17 08:14 UTC, setiat commented on ids_validator/checks/generic/root_node.py
> +                        f"'root.type' is {node.type_}. It must be set to 'object'",
fixed.

2022-02-17 08:14 UTC, setiat commented on ids_validator/checks/generic/type_check.py
> +                        (f"'{node.path}.{key}' has no 'type' defined", Log.CRITICAL)
fixed.

2022-02-17 08:15 UTC, setiat commented on ids_validator/ids_node.py
> +        return True if "type" in self.data else False
Removed it. This was no longer needed.

2022-02-17 08:15 UTC, setiat commented on __tests__/unit/generic/files/type_check/invalid_missing_type.json
> +    "beta": {}
added

2022-02-18 10:57 UTC, robjhornby-ts approved these changes
Looks good, thanks!

2022-02-18 12:05 UTC, mlipschultz approved these changes

2022-02-18 13:23 UTC, merged