DE-3256: fix package error
tetrascience/ts-ids-validator pull request #42
Opened 2022-02-18 13:41 UTC by setiat

Updated jsonschema to 4.4.0
Tested locally, no error logged

Logs when current version of  packages are fetched from pypi:
[pypi.log](https://github.com/tetrascience/ts-ids-validator/files/8097576/pypi.log)

Logs when new new ids validator  is fetched from local pypi server:
[new_package_local_pypi.log](https://github.com/tetrascience/ts-ids-validator/files/8097598/new_package_local_pypi.log)

2022-02-18 13:48 UTC, mlipschultz requested changes

2022-02-18 13:48 UTC, mlipschultz commented on Pipfile
> +jsonschema = ">=4.0.0"
This should be `">4.0.0"` since there was a problem with 4.0.0.  I think that version's no longer available, but just in case it'd be good to exclude it.

2022-02-18 13:48 UTC, mlipschultz commented on README.md
> +- Update `jsonschema` version to `4.4.0`
This is probably minor, but that's not entirely accurate.  If someone adds a new dependency to this project, jsonschema might get upgraded in the process.  I think it's more accurate to say:
```suggestion
- Update `jsonschema` version to `4`
```
Although I don't like this much either.  Maybe "Update `jsonschema` to 4.0.1 or above".  If you can think of something better, feel free to use that

2022-02-18 14:08 UTC, setiat commented on Pipfile
> +jsonschema = ">=4.0.0"
fixed.

2022-02-18 14:08 UTC, setiat commented on README.md
> +- Update `jsonschema` version to `4.4.0`
changed it to : Update `jsonschema` version to fix package installation error
Let me know if it works

2022-02-18 14:11 UTC, setiat commented
@mlipschultz 

If I lock the python version to 3.7 code build fails....GIthuba action is not able to find required python 3.7 images.Is this is a known issue?

However... I do want to lock python 3.7 because this is what we use in artifact builder.

2022-02-18 18:19 UTC, mlipschultz approved these changes
It looks good to me.  Once the python issue is resolved (hint @abclay), I think it's good to merge!

2022-02-18 22:21 UTC, abclay commented
I just merged an update to the core github action.  To pick up those changes, I would recommend rebasing your branch and pushing it again.

I tried that, and some tests were still failing.  It looks like `importlib_metadata` is available in the travis env, but not in Github Actions.  When I added it to the pipenv, everything seems to work.  You can see my changes here: https://github.com/tetrascience/ts-ids-validator/pull/43

2022-02-22 14:47 UTC, abclay approved these changes

2022-02-23 12:15 UTC, merged