DE-3468: make source models consistent
tetrascience/ts-ids-validator pull request #46
Opened 2022-04-01 15:31 UTC by robjhornby-ts

## JIRA ticket

https://tetrascience.atlassian.net/browse/DE-3468

## Description

Note: I'll clean up some of the code problems shown by github-actions, but this PR is already touching a lot of files because of pre-commit; I'll leave the rest of the tidying until some initial review is done.

@VladimirShteyn added for optional code review only if you have time, don't spend too long on it but I wonder what your opinions are on how to keep this code tidy.

In our current [samples template](https://developers.tetrascience.com/docs/ids-design-conventions-schema-templates#samples), `samples[*].properties[*].source.name`  is a nullable string, but `samples[*].labels[*].source.name` is of type string. Apart from this type difference, the two source objects are identical. This comes from the way they were documented in our external docs, but both source objects should be allowed to have the same schema so that they can use the same `source` model in PIDS.

Updated the validator to:

- Introduce a backward-compatible type check, with a "preferred" type and one or more "deprecated" types.
- Raise a warning if `samples[*].labels[*].source.name` is of type string (don’t fail validation with an error, otherwise every current IDS would fail IDS validation)
- Allow `samples[*].labels[*].source.name` to be a `nullable_string`
- No change to the `samples[*].properties[*].source.name` checks, it’s already of type `nullable_string` which is what we want

## Supporting test data

## Automated testing

- [x] Unit tests
  - Updated all other tests to have a `properties source name` of type nullable_string
  - Added a test where the `properties source name` has type string, asserting that a warning is raised
- [ ] Integration tests
- [ ] API tests
- [ ] End-To-End tests
- [ ] N/A (please clarify)

2022-04-07 16:53 UTC, apjansing requested changes
Nothing huge and one is out of scope

2022-04-07 16:53 UTC, apjansing commented on README.md
> +    - `"required"`, `list`: The required list of the `Node` must only contain values listed in `required`
Since we started using `List[str]` above, should these be `List[<type>]`?

2022-04-07 16:53 UTC, apjansing commented on __tests__/unit/validate_ids/files/valid_ids/schema.json
>                "properties": {
Just something I saw in `__tests__/unit/v1/files/samples_node/both_missing_and_extra_property.json`

This is for the object above: https://github.com/tetrascience/ts-ids-validator/pull/46/files#diff-c317344fbbc3be12ab2b4c5fe294eb63bbd78bb62b2590b7cd6750626653217fR193-R198 
Are some items like `column` and `row` valid candidates for `nullable_integer`?

2022-04-07 16:53 UTC, apjansing commented on __tests__/unit/validate_ids/files/valid_ids/schema.json
> +                  "type": ["string", "null"],
`nullable_string`

2022-04-07 16:53 UTC, apjansing commented on __tests__/unit/validate_ids/files/valid_ids/schema.json
> +                  "type": ["number", "null"],
`nullable_string`

2022-04-07 16:53 UTC, apjansing commented on __tests__/unit/validate_ids/files/valid_ids/schema.json
> +                  "type": ["boolean", "null"],
`nullable_boolean`

2022-04-24 11:02 UTC, setiat approved these changes
Nice implementation! Approved.

As a follow-up task, do you think its a good idea to convert all `type` rules to `compatible_type` rules?

2022-04-26 16:06 UTC, robjhornby-ts commented on README.md
> +    - `"required"`, `list`: The required list of the `Node` must only contain values listed in `required`
Good point, updated all the type hints in this list

2022-04-26 16:35 UTC, robjhornby-ts commented on __tests__/unit/validate_ids/files/valid_ids/schema.json
> +                  "type": ["string", "null"],
changed

2022-04-26 16:35 UTC, robjhornby-ts commented on __tests__/unit/validate_ids/files/valid_ids/schema.json
> +                  "type": ["number", "null"],
changed

2022-04-26 16:36 UTC, robjhornby-ts commented on __tests__/unit/validate_ids/files/valid_ids/schema.json
> +                  "type": ["boolean", "null"],
changed

2022-04-27 17:20 UTC, apjansing approved these changes

2022-04-27 17:49 UTC, merged